version: "2.4"
services:
  backend:
    image: $CI_REGISTRY_IMAGE:$DOCKERIMAGE_TAG
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: open_state
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD
  redis:
    image: redis
    ports:
      - 6379:6379
