version: '3.1'

services:

  open-state-mongo:
    image: mongo
    container_name: open-state-mongo
    restart: always
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  open-state-redis:
    image: redis
    container_name: open-state-redis
    ports:
      - "6380:6379"