CREATE TABLE states
(
    id BIGSERIAL PRIMARY KEY,
    root VARCHAR(64) NOT NULL
);

CREATE TABLE integrations
(
    id BIGSERIAL PRIMARY KEY,
    address VARCHAR(64) NOT NULL,
    balance BIGINT NOT NULL DEFAULT 0,
    state_id BIGINT REFERENCES states,
    disabled BOOLEAN NOT NULL DEFAULT FALSE
);
