ALTER TABLE wallets
    ADD COLUMN is_active BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE states
    ALTER COLUMN balance TYPE BIGINT,
    ALTER COLUMN balance SET NOT NULL,
    ALTER COLUMN balance SET DEFAULT 0;
